### ISSUE TITLE
Resurrected Eye Missing From Volcanic Cave

### ISSUE THREAD

**Issue by danielbporter** [Silberdrachi/CanIIdle#11]
Resurrected Eye, the fourth monster encountered in the Volcanic Cave, does not appear in the monster list for the Volcanic Cave dungeon. I think this is because the monster's name is "Resurrected Eye," but the name in the monster list (index.html line 586) is "The Resurrected Eye."

https://github.com/Silberdrachi/CanIIdle/blob/031b2ca94723921e77d81b9d3776af79ba0730c8/index.html#L586

https://wiki.melvoridle.com/w/Volcanic_Cave

Thank you for the great tool!

**Comment by Silberdrachi** [comment]
Yep that was the problem. I fixed that and another ordering issue, should be good now.
