### ISSUE TITLE
Slayer calc is incorrect

### ISSUE THREAD

**Issue by FuzzyDK** [Silberdrachi/CanIIdle#14]
Master Slayer . Ranged. Eat3. 71 dr +3dr from summons bonus. Plus 10% dr pot 970 HP died to Slayer task because sure said green not counting one enemy
![Screenshot_20211222-050557](https://user-images.githubusercontent.com/96524339/147076854-97344461-4eed-46d9-b961-25459d58b270.png)
![Screenshot_20211222-050543](https://user-images.githubusercontent.com/96524339/147076857-797d2fc4-663e-4ba2-b4a7-06be51cd4819.png)
Hoping can be fixed so other people don't lose gear or HC like me

**Comment by Silberdrachi** [comment]
Yes, ill add the same orange formatting to the overview page. 

I highly highly wouldnt suggest idling master tasks either way.

**Comment by Silberdrachi** [comment]
Resolved, updated highlighting and added icons with tooltips on the monsters themselves to provide explanations.
