### ISSUE TITLE
Incorrect damage for Blue Dragon in Adventure Mode

### ISSUE THREAD

**Issue by Dalayeth** [Silberdrachi/CanIIdle#2]
In Standard Mode the damage of Blue Dragon is 168. Normally damage in Adventure Mode seems to be just multiplied by 10 but in this case the damage of the Blue Dragon is actually 1,688. It's probably just rounded down in Standard Mode. This is a small difference but it happened to be the difference between being able to idle it and not being able to for me. There was no death I just wanted you to know that some damages might be slightly different on Adventure Mode because it might be rounded down in Standard.

**Comment by Dalayeth** [comment]
I looked into this issue a bit and found that it is a little more complicated than just multiplying every number by 10. While that is effectively what it's doing they do it before calculations which makes a difference. The only fix would be to add a new  value to the table of every enemy that has its max hit for Adventure Mode or to calculate it like the game does. I don't have access to every enemy on Adventure Mode yet but if we go the calculate route it would be pretty easy to get all the enemies and make it future proof when they add more too. The list of in game monsters and their data can be found [here](https://melvoridle.com/assets/js/game/monsters.js?832). The damage calculation for enemies looks like it is mostly the same as for players.

```
function calculateEnemyStrength(enemy = enemyInCombat) {
    if (enemy !== null && enemy !== undefined) {
        if (combatData.enemy.attackType === CONSTANTS.attackType.Melee) {
            combatData.enemy.effectiveStrengthLevel = Math.floor(combatData.enemy.strengthLevel + 8 + 1);
            combatData.enemy.maximumStrengthRoll = Math.floor(numberMultiplier * (1.3 + combatData.enemy.effectiveStrengthLevel / 10 + combatData.enemy.strengthBonus / 80 + (combatData.enemy.effectiveStrengthLevel * combatData.enemy.strengthBonus) / 640));
        } else if (combatData.enemy.attackType === CONSTANTS.attackType.Ranged) {
            combatData.enemy.effectiveStrengthLevel = Math.floor(combatData.enemy.rangedLevel + 8 + 1);
            combatData.enemy.maximumStrengthRoll = Math.floor(numberMultiplier * (1.3 + combatData.enemy.effectiveStrengthLevel / 10 + combatData.enemy.strengthBonusRanged / 80 + (combatData.enemy.effectiveStrengthLevel * combatData.enemy.strengthBonusRanged) / 640));
        } else if (combatData.enemy.attackType === CONSTANTS.attackType.Magic) {
            if (!isGolbinRaid) {
                if (MONSTERS[enemy].selectedSpell === null || MONSTERS[enemy].selectedSpell === undefined) combatData.enemy.maximumStrengthRoll = Math.floor(numberMultiplier * (MONSTERS[enemy].setMaxHit + MONSTERS[enemy].setMaxHit * (combatData.enemy.damageBonusMagic / 100)));
                else combatData.enemy.maximumStrengthRoll = Math.floor(numberMultiplier * (SPELLS[MONSTERS[enemy].selectedSpell].maxHit + SPELLS[MONSTERS[enemy].selectedSpell].maxHit * (combatData.enemy.damageBonusMagic / 100)));
            } else {
                combatData.enemy.effectiveStrengthLevel = Math.floor(combatData.enemy.magicLevel + 8 + 1);
                combatData.enemy.maximumStrengthRoll = Math.floor(numberMultiplier * (1.3 + combatData.enemy.effectiveStrengthLevel / 10 + combatData.enemy.magicStrengthBonus / 80 + (combatData.enemy.effectiveStrengthLevel * combatData.enemy.magicStrengthBonus) / 640));
            }
        }
    }
}
```

Then it just does damage reduction and formats it.

```
function updateEnemyMaxHit() {
    if (isInCombat && !newEnemyLoading) {
        if (damageReduction > 0) $("#combat-enemy-strength-bonus").text("(" + numberWithCommas(Math.floor(combatData.enemy.maximumStrengthRoll * (1 - damageReduction / 100))) + ")");
        else $("#combat-enemy-strength-bonus").text(numberWithCommas(combatData.enemy.maximumStrengthRoll));
    }
}
```

The code for the combat stuff can be found [here](https://melvoridle.com/assets/js/game/combat.js?832)

**Comment by Silberdrachi** [comment]
Sorry this was fixed ages back and i shouldve closed this out. I have fully changed over to using actual level calculation of damage in early .20 release of Melvor Idle. Though this needs to be updated for .21 as the formula have changed for some things.
