### ISSUE TITLE
Add weakining calculations for magic style

### ISSUE THREAD

**Issue by VanWeapon** [Silberdrachi/CanIIdle#20]
When using magic there are 3 tiers of weakening curse you can apply, applying -5%, -10%, and -15% max hit to the enemy respectively. 
Would this lower the base DR% needed to idle certain dungeons? If so can this be added to the advanced options?

**Comment by Silberdrachi** [comment]
Id rather not as its not actually 100% true. If you miss enough times or if it hits you hard before you can weaken it, it will be using its normal damage. CII is intended to show the bare minimum of exactly what you need to be safe. For something like that id suggest using something like combat sim where it can determine what the % chance of death is and you can make a judgement call on if you feel its sufficient
