### ISSUE TITLE
Combat Triangle in "Internal Suffering Mode"

### ISSUE THREAD

**Issue by Sandstroem** [Silberdrachi/CanIIdle#21]
Are you sure the combat triangle is correct in the new mode?

I selected dragons den, which is a dungeon full of melee hostiles.

According to the calc I need the least amount of DR with melee, followed by ranged and then the highest with magic.
If I understand it correctly, the new triangle is the opposite of the old one, so it should be ranged -> melee -> magic from least to highest amount of DR needed.

Another example: Hall of wizards, full of magic

Calc says magic > melee > ranged, I would have expected melee > magic > ranged (from lowest DR needed to highest)

**Comment by Sandstroem** [comment]
Another example: Hall of wizards, full of magic

Calc says magic > melee > ranged, I would have expected melee > magic > ranged

**Comment by Silberdrachi** [comment]
Pushed changes for this fix, shifted the array incorrectly
