### ISSUE TITLE
Dungeon tab does not include the "Strange Cave" dungeon.

### ISSUE THREAD

**Issue by SoloJessy** [Silberdrachi/CanIIdle#22]
The monsters are included in the monster lists. but there is no grouping in the dungeon tab.

**Comment by Silberdrachi** [comment]
Strange cave isnt a dungeon, its a slayer area. Slayer areas arent broken up that way, they are broken up by task tier.

**Comment by SoloJessy** [comment]
Never mind me, its called a dungeon on the wiki. and i took that as gospel without checking.

**Comment by SoloJessy** [comment]
Or im just blind, you can just ignore this completely xD
