### ISSUE TITLE
Feature Request: Suggested gear for max DR and damage?

### ISSUE THREAD

**Issue by manojchandrashekar** [Silberdrachi/CanIIdle#3]
Is it possible to suggest gear to reach the DR levels needed with different combat styles?

The wiki has this information but it is limited to a single combat style and I'm not sure if it is up to date.

**Comment by Silberdrachi** [comment]
This is beyond the scope of what the idle calculations are designed to do as it would be too difficult to make assumptions of the players level or the pieces of gear they have access to. On the wiki there are guides for some dungeons as well as there is the Combat Sim that can be more effective at showing those combinations.

**Comment by manojchandrashekar** [comment]
It isn't really about what the players have access to. It's more about what they need to have to be able to reach the DR level needed.

But I understand if it is out of scope. Thanks.
