### ISSUE TITLE
Incorrect max hits

### ISSUE THREAD

**Issue by Pyko0** [Silberdrachi/CanIIdle#6]
With the rewrite of combat multiple max hits have been reduced or altered. Eg. Malcs' (Volcanic cave) max hit went up by 1 while Malcs' (Infernal Stronghold) max hit went down by +- 100. Atleast that's what I deduce from reading the patch notes combined with my personal experience.

**Comment by Silberdrachi** [comment]
Do you have an example of where the UI doesnt match what youre seeing in game? CII should be up to date using all the new monster stats. If you can use that 'copy link' button on the website that would work to give me all the relevant information, as well as a screen shot from in game showing your gear/hp/potion/prayer and the enemy stats

**Comment by Pyko0** [comment]
Example

My ingame stats showing
1030 hp, 51% DR, and the monsters max hit of 287 (normal attack) from Glacia
https://i.gyazo.com/f4589499551f1f90be2f266dda4ecda5.png

The website showing a max hit of 375 (normal attack) from Glacia
https://silberdrachi.github.io/CanIIdle/?totalHealth=1030&currentDR=51&autoEatLevel=3&combatStyle=Ranged&gameMode=Normal&yakSynergy=None&wastefulRing=No&guardianAmulet=No

**Comment by Silberdrachi** [comment]
Strange. It shouldnt be that far off ever.
Can you give me a screen shot when youre out of combat as well. The data from that equipment window is not accurate at all. It doesnt take into account pets, synergies, agility, potions or prayers.

**Comment by Pyko0** [comment]
The example is kind of wonky though, the max hit difference is that big due to a 30% damage increase debuff I wasn't acounting for

The actual max hit here ingame is 374.

**Comment by Pyko0** [comment]
The same gear etc ooc:

https://i.gyazo.com/8e8b435e50b2eed07778e9df4e2bbf45.png

**Comment by Silberdrachi** [comment]
Sounds like youre saying its just off by 1 on the max hit? That is normal. There is some rounding going on that results in the UI being possibly 1 dmg lower than the max hit. CII is accounting for that just in case. 

CII always shows all damage as if youre stunned, because that is the true max hit of the enemy.

**Comment by Pyko0** [comment]
Roger, I'm going to hit you with another example though. This being the one that triggered this course of thinking.

Ingame stats:
1110 HP, 48% DR, No prayers, synergies, potions
Infernal stronghold Malcs max hit: 458 (when stunned)
(this is my gf's game rn)

Website showing max hit of 467
https://silberdrachi.github.io/CanIIdle/?totalHealth=1110&currentDR=48&autoEatLevel=3&combatStyle=Melee&gameMode=Normal&yakSynergy=None&wastefulRing=No&guardianAmulet=No

**Comment by Silberdrachi** [comment]
Are you sure its 48 DR? Or is that 48 dr on their equipment? Because that 458 matches with 49 dr, and if they had something like the defensive pet (leonardo) that would give you +1 DR.

**Comment by Pyko0** [comment]
that is exactly what's going on, thanks.

**Comment by Silberdrachi** [comment]
![image](https://user-images.githubusercontent.com/76179203/132036357-5f5e6452-dd2e-45e6-b105-300fa94a00c2.png)

In the future id suggest getting the DR value when youre out of combat, from this section of the combat window. This will include ALL buffs and debuffs to your DR when out of combat. Then the website will be able to calculate the in-combat DR for you.

**Comment by Pyko0** [comment]
Will do, thanks for the quick response!
