### ISSUE TITLE
Increased max hit on stun not being calculated

### ISSUE THREAD

**Issue by TBthe1** [Silberdrachi/CanIIdle#7]
Doing the Air god dungeon with following stats:
930 hp - 48 dr (out of combat) - food treshold (tier 3) on 372hp

According to the tool I should be able to idle this dungeon but...
Aleron --> melee so 48 dr --> max hit = 363 --> no stun --> safe
Aeris -->  ranged enemy so DR is X 1,25 = 60 --> max hit = 338 --> stunned max hit (+30% damage) =  440
(according to the Wiki page, the max hit is 780 BUT in game the max hit (normal attack) is 847 in the collection log/combat https://wiki.melvoridle.com/w/Aeris)

Aeris has a 20% chance on a ranged attack called Whirlwind: 
"Launch a large avoidable gust of wind that deals 550 damage. On a hit, applies stun for 1 turn."
While a player or monster is stunned, they take 30% more damage. This is the crucial part.

If i'm stunned I receive 30% more damage (in this case for 1 turn) , that increases the max hit from a normal attack to 440 (847 normal attack * 0,4 from DR = 338.8, then with stun it makes 338.8 max hit * 1.3 = 440.44) which  is more than 372 so Aeris should be able to kill me. 

I assume this calculation isn't globally implemented for all the mobs with a stun effect?

**Comment by Silberdrachi** [comment]
Aeris shouldn't use its normal attack, so i am confused. CII doesn't show the normal attack at all if the enemy doesn't use it. Are you saying you were hit by a normal attack?

**Comment by TBthe1** [comment]
Just asked the question on the Discord server and seems they fixed this bug in V0.19.1:
[FIXED] Some Enemies are able to activate a Normal Attack when they shouldn't be able to (Eg. Aeris)

I also didn't knew how to assume a mob can't do normal attacks (if all the special attacks equal to 100%), and when the game updated the normal attack while I was being stunned I got afraid to die.

Sorry for the overload of information!
